//
// Created by HanWool on 2017. 11. 17..
//

#ifndef NXPIOTCONTROLBRIDGEPARSER_ENUMS_H
#define NXPIOTCONTROLBRIDGEPARSER_ENUMS_H
typedef enum E_MESSAGE_COMMAND_TYPE {
    E_COMMON_MODULE_MSG_NULL = 0xFFFF,
    E_COMMON_MODULE_MSG_STATUS = 0x8000,// Common Commands
    E_COMMON_MODULE_MSG_LOG = 0x8001,

    E_COMMON_MODULE_MSG_DATA_INDICATION = 0x8002,

    E_COMMON_MODULE_MSG_NODE_CLUSTER_LIST  = 0x8003,
    E_COMMON_MODULE_MSG_NODE_ATTRIBUTE_LIST = 0x8004,
    E_COMMON_MODULE_MSG_NODE_COMMAND_ID_LIST  = 0x8005,

    E_COMMON_MODULE_MSG_GET_VERSION  = 0x0010,
    E_COMMON_MODULE_MSG_VERSION_LIST = 0x8010,

    E_COMMON_MODULE_MSG_SET_EXT_PANID = 0x0020,
    E_COMMON_MODULE_MSG_SET_CHANNELMASK = 0x0021,
    E_COMMON_MODULE_MSG_SET_SECURITY = 0x0022,
    E_COMMON_MODULE_MSG_SET_DEVICETYPE  = 0x0023,
    E_COMMON_MODULE_MSG_START_NETWORK = 0x0024,
    E_COMMON_MODULE_MSG_START_SCAN = 0x0025,
    E_COMMON_MODULE_MSG_NETWORK_JOINED_FORMED = 0x8024,

    E_COMMON_MODULE_MSG_RESET  = 0x0011,
    E_COMMON_MODULE_MSG_ERASE_PERSISTENT_DATA = 0x0012,
    E_COMMON_MODULE_MSG_ZLL_FACTORY_NEW = 0x0013,
    E_COMMON_MODULE_MSG_BIND = 0x0030,
    E_COMMON_MODULE_MSG_UNBIND = 0x0031,

    E_COMMON_MODULE_MSG_NETWORK_ADDRESS_REQUEST  = 0x0040,
    E_COMMON_MODULE_MSG_IEEE_ADDRESS_REQUEST  = 0x0041,
    E_COMMON_MODULE_MSG_NODE_DESCRIPTOR_REQUEST  = 0x0042,
    E_COMMON_MODULE_MSG_SIMPLE_DESCRIPTOR_REQUEST = 0x0043,
    E_COMMON_MODULE_MSG_SIMPLE_DESCRIPTOR_RESPONSE  = 0x8043,
    E_COMMON_MODULE_MSG_POWER_DESCRIPTOR_REQUEST = 0x0044,
    E_COMMON_MODULE_MSG_ACTIVE_ENDPOINT_REQUEST  = 0x0045,
    E_COMMON_MODULE_MSG_MATCH_DESCRIPTOR_REQUEST = 0x0046,
    E_COMMON_MODULE_MSG_MATCH_DESCRIPTOR_RESPONSE = 0x8046,
    E_COMMON_MODULE_MSG_MANAGEMENT_LEAVE_REQUEST = 0x0047,
    E_COMMON_MODULE_MSG_LEAVE_CONFIRMATION = 0x8047,
    E_COMMON_MODULE_MSG_LEAVE_INDICATION = 0x8048,
    E_COMMON_MODULE_MSG_PERMIT_JOINING_REQUEST = 0x0049,
    E_COMMON_MODULE_MSG_MANAGEMENT_NETWPRK_UPDATE_REQUEST =0x004A,
    E_COMMON_MODULE_MSG_SYSTEM_SERVER_DISCOVERY  = 0x004B,
    E_COMMON_MODULE_MSG_COMPLEX_DESCRIPTOR_REQUEST  = 0x004C,
    E_COMMON_MODULE_MSG_DEVICE_ANNOUNCE = 0x004D,
    E_COMMON_MODULE_MSG_MANAGEMENT_LQI_REQUEST = 0x004E,
    E_COMMON_MODULE_MSG_MANAGEMENT_LQI_RESPONSE  = 0x804E,

    E_COMMON_GROUP_CL_MSG_ADD_GROUP = 0x0060,// Group Cluster
    E_COMMON_GROUP_CL_MSG_VIEW_GROUP = 0x0061,
    E_COMMON_GROUP_CL_MSG_GET_GROUP_MEMBERSHIP  = 0x0062,
    E_COMMON_GROUP_CL_MSG_GET_GROUP_MEMBERSHIP_RESPONSE  = 0x8062,
    E_COMMON_GROUP_CL_MSG_REMOVE_GROUP = 0x0063,
    E_COMMON_GROUP_CL_MSG_REMOVE_ALL_GROUPS  = 0x0064,
    E_COMMON_GROUP_CL_MSG_ADD_GROUP_IF_IDENTIFY = 0x0065,

    E_COMMON_IDENTIFY_CL_MSG_IDENTIFY_SEND = 0x0070,// Identify Cluster
    E_COMMON_IDENTIFY_CL_MSG_IDENTIFY_QUERY  = 0x0071,

    E_COMMON_LEVEL_CL_MSG_MOVE_TO_LEVEL = 0x0080,// Level Cluster
    E_COMMON_LEVEL_CL_MSG_MOVE_TO_LEVEL_ONOFF = 0x0081,
    E_COMMON_LEVEL_CL_MSG_MOVE_STEP = 0x0082,
    E_COMMON_LEVEL_CL_MSG_MOVE_STOP_MOVE  = 0x0083,
    E_COMMON_LEVEL_CL_MSG_MOVE_STOP_ONOFF = 0x0084,

    E_COMMON_ONOFF_CL_MSG_NOEFFECTS = 0x0092,// On/Off Cluster
    E_COMMON_ONOFF_CL_MSG_TIMED  = 0x0093,
    E_COMMON_ONOFF_CL_MSG_EFFECTS = 0x0094,

    E_COMMON_SCENE_CL_MSG_VIEW_SCENE = 0x00A0,// Scenes Cluster
    E_COMMON_SCENE_CL_MSG_ADD_SCENE = 0x00A1,
    E_COMMON_SCENE_CL_MSG_REMOVE_SCENE = 0x00A2,
    E_COMMON_SCENE_CL_MSG_REMOVE_ALL_SCENES  = 0x00A3,
    E_COMMON_SCENE_CL_MSG_STORE_SCENE  = 0x00A4,
    E_COMMON_SCENE_CL_MSG_RECALL_SCENE = 0x00A5,
    E_COMMON_SCENE_CL_MSG_SCENE_MEMBERSHIP_REQUEST = 0x00A6,

    E_COMMON_COLOUR_CL_MSG_MOVE_TO_HUE  = 0x00B0,// Colour Cluster
    E_COMMON_COLOUR_CL_MSG_MOVE_HUE  = 0x00B1,
    E_COMMON_COLOUR_CL_MSG_STEP_HUE  = 0x00B2,
    E_COMMON_COLOUR_CL_MSG_MOVE_TO_SATURATION = 0x00B3,
    E_COMMON_COLOUR_CL_MSG_MOVE_SATURATION = 0x00B4,
    E_COMMON_COLOUR_CL_MSG_STEP_SATURATION = 0x00B5,
    E_COMMON_COLOUR_CL_MSG_MOVE_TO_HUE_SATURATION = 0x00B6,
    E_COMMON_COLOUR_CL_MSG_MOVE_TO_COLOUR  = 0x00B7,
    E_COMMON_COLOUR_CL_MSG_MOVE_COLOUR  = 0x00B8,
    E_COMMON_COLOUR_CL_MSG_STEP_COLOUR  = 0x00B9,

    E_ZLL_TOUCHLINK_MSG_INITIATE = 0x00D0,// ZLL Touchlink
    E_ZLL_TOUCHLINK_MSG_TSTATUS = 0x00D1,
    E_ZLL_TOUCHLINK_MSG_FACTORY_RESET  = 0x00D2,

    E_ZLL_IDENTIFY_CL_MSG_TRIGGER_EFFECT  = 0x00E0,// ZLL Identify Cluster

    E_ZLL_SCENE_CL_MSG_ADD_ENHANCED_SCENE = 0x00A7,// ZLL Scenes Cluster
    E_ZLL_SCENE_CL_MSG_VIEW_ENHANCED_SCENE = 0x00A8,
    E_ZLL_SCENE_CL_MSG_COPY_SCENE = 0x00A9,

    E_ZLL_COLOUR_CL_MSG_ENHANCED_MOVE_TO_HUE  = 0x00BA,// ZLL Colour Cluster
    E_ZLL_COLOUR_CL_MSG_ENHANCED_MOVE_HUE  = 0x00BB,
    E_ZLL_COLOUR_CL_MSG_ENHANCED_STEP_HUE  = 0x00BC,
    E_ZLL_COLOUR_CL_MSG_ENHANCED_MOVE_TO_HUE_SATURATION =  0x00BD,
    E_ZLL_COLOUR_CL_MSG_COLOUR_LOOP_SET = 0x00BE,
    E_ZLL_COLOUR_CL_MSG_STOP_MOVE_STEP  = 0x00BF,
    E_ZLL_COLOUR_CL_MSG_MOVE_TO_COLOUR_TEMPERATURE  = 0x00C0,
    E_ZLL_COLOUR_CL_MSG_MOVE_COLOUR_TEMPERATURE  = 0x00C1,
    E_ZLL_COLOUR_CL_MSG_STEP_COLOUR_TEMPERATURE  = 0x00C2,

    E_ZHA_DOORLOCK_CL_MSG_LOCK_UNLOCK_DOOR = 0x00F0,// ZHA Door Lock Cluster
    E_ZHA_DOORLOCK_CL_MSG_READ_ATTRIBUTE_REQUEST = 0x0100,
    E_ZHA_DOORLOCK_CL_MSG_READ_ATTRIBUTE_RESPONSE  = 0x8100,
    E_ZHA_DOORLOCK_CL_MSG_SAVE_PDM_RECORD = 0x0200,
    E_ZHA_DOORLOCK_CL_MSG_SAVE_PDM_RECORD_RESPONSE = 0x8200,
    E_ZHA_DOORLOCK_CL_MSG_LOAD_PDM_RECORD_REQUEST  = 0x0201,
    E_ZHA_DOORLOCK_CL_MSG_LOAD_PDM_RECORD_RESPONSE = 0x8201,
    E_ZHA_DOORLOCK_CL_MSG_DELETE_PDM_RECORD  = 0x0202,
    E_ZHA_DOORLOCK_CL_MSG_PDM_HOST_AVAILABLE = 0x0300,
    E_ZHA_DOORLOCK_CL_MSG_PDM_HOST_AVAILABLE_RESPONSE = 0x8300,
} eMessageCommandType;

typedef enum E_PARSING_STATUS {
    E_PARSING_OK,
    E_PARSING_ERR_START_BYTE_IS_NOT_STX,
    E_PARSING_ERR_ENDLESS_STREAM,
    E_PARSING_ERR_CHECKSUM,
    E_PARSING_ERR_DATA_LENGTH,
} eParsingStatus;

typedef enum E_MODULE_STATUS {
    E_MODULE_STATUS_OK = 0,
    E_MODULE_STATUS_INCORRECT_PARAM,
    E_MODULE_STATUS_UNHANDELED_COMMAND,
    E_MODULE_STATUS_COMMAND_FAILED,
    E_MODULE_STATUS_MODULE_BUSY,
    E_MODULE_STATUS_STACK_ALREADY_STARTED
} eModuleStatus;

typedef enum E_NETWORK_JOIN_FORM_STATUS {
    JOINED_EXISTING_NET = 0,
    FORMED_NEW_NET = 1,
} eNetworkJoinFormStatus;

typedef enum E_LOG_LEVEL {
    EMERG = 0,
    ALERT,
    CRIT,
    ERROR,
    WARN,
    NOTICE,
    INFO,
    DEBUG
} eLogLevel;

//enum E_CHANNEL {
//};
#endif //NXPIOTCONTROLBRIDGEPARSER_ENUMS_H
